### ISSUE TITLE
你好，我使用这个你的EFI ，安装出现禁行标志

### ISSUE THREAD

**Issue by RootSir** [BrushXue/Z170i-Pro-Gaming-Hackintosh#1]
我的主板和你的一样的，显卡是HD530核显，如果知道原因可以告诉我吗？谢谢

**Comment by BrushXue** [comment]
> 我的主板和你的一样的，显卡是HD530核显，如果知道原因可以告诉我吗？谢谢

请问你是单核显还是有独立显卡？

**Comment by RootSir** [comment]
> > 我的主板和你的一样的，显卡是HD530核显，如果知道原因可以告诉我吗？谢谢
> 
> 我刚才用U盘试了一次，可以正常走到Disk Utility抹除磁盘那一步。请问你是单核显还是有独立显卡？
不好意思，我刚才搞错了，现在报这个错误安装的时候，然后就重启了
problem with memory panic stackshot succeeded ** bytes traced 262464 **
Attempting system restart...

**Comment by RootSir** [comment]
> > 我的主板和你的一样的，显卡是HD530核显，如果知道原因可以告诉我吗？谢谢
> 
> 我刚才用U盘试了一次，可以正常走到Disk Utility抹除磁盘那一步。请问你是单核显还是有独立显卡？

不好意思，我刚才搞错了，现在报这个错误安装的时候，然后就重启了
problem with memory panic stackshot succeeded ** bytes traced 262464 **
Attempting system restart...

**Comment by BrushXue** [comment]
> > > 我的主板和你的一样的，显卡是HD530核显，如果知道原因可以告诉我吗？谢谢
> > 
> > 
> > 我刚才用U盘试了一次，可以正常走到Disk Utility抹除磁盘那一步。请问你是单核显还是有独立显卡？
> 
> 不好意思，我刚才搞错了，现在报这个错误安装的时候，然后就重启了,没有独立显卡，只有核显。
> problem with memory panic stackshot succeeded ** bytes traced 262464 **
> Attempting system restart...

因为我把核显设置为headless模式，没有输出。
你试着把config.plist里面关于核显的那一段改一下
原本的
```
            <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
            <dict>
                <key>AAPL,ig-platform-id</key>
                <data>
                AAASGQ==
                </data>
                <key>framebuffer-patch-enable</key>
                <data>
                AQAAAA==
                </data>
                <key>framebuffer-stolenmem</key>
                <data>
                AAAwAQ==
                </data>
            </dict>
```
替换为
```
            <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
            <dict>
                <key>AAPL,ig-platform-id</key>
                <data>
                AAASGQ==
                </data>
                <key>framebuffer-patch-enable</key>
                <data>
                AQAAAA==
                </data>
                <key>framebuffer-stolenmem</key>
                <data>
                AAAwAQ==
                </data>
            </dict>
```

**Comment by RootSir** [comment]
> > > > 我的主板和你的一样的，显卡是HD530核显，如果知道原因可以告诉我吗？谢谢
> > > 
> > > 
> > > 我刚才用U盘试了一次，可以正常走到Disk Utility抹除磁盘那一步。请问你是单核显还是有独立显卡？
> > 
> > 
> > 不好意思，我刚才搞错了，现在报这个错误安装的时候，然后就重启了,没有独立显卡，只有核显。
> > problem with memory panic stackshot succeeded ** bytes traced 262464 **
> > Attempting system restart...
> 
> 因为我把核显设置为headless模式，没有输出。
> 你试着把config.plist里面关于核显的那一段改一下
> 原本的
> 
> ```
> 			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
> 			<dict>
> 				<key>AAPL,ig-platform-id</key>
> 				<data>AQASGQ==</data>
> 				<key>device-id</key>
> 				<data>EhkAAA==</data>
> 				<key>framebuffer-patch-enable</key>
> 				<data>AQAAAA==</data>
> 			</dict>
> ```
> 
> 替换为
> 
> ```
>             <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
>             <dict>
>                 <key>AAPL,ig-platform-id</key>
>                 <data>
>                 AAASGQ==
>                 </data>
>                 <key>framebuffer-patch-enable</key>
>                 <data>
>                 AQAAAA==
>                 </data>
>                 <key>framebuffer-stolenmem</key>
>                 <data>
>                 AAAwAQ==
>                 </data>
>             </dict>
> ```
> 
> [这里有更详细的解释](https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/skylake#properties)

太感谢了，谢谢你。
