### ISSUE TITLE
您好，我遇到了睡死的问题

### ISSUE THREAD

**Issue by fishlzhy** [BrushXue/Z170i-Pro-Gaming-Hackintosh#2]
您好，我使用的是您提供的EFI安装的系统，目前我使用的是6700K的集显，相应部分的config也是根据之前一个issues您提供的内容修改好的，现在系统是已经安装完成可以使用的，我的SSD是SM951的512G，但是我发现系统自动休眠后无法唤醒，主动睡眠的话，唤醒会自动关机再重启，想问一下您这里是否有解决思路？感谢！

**Comment by BrushXue** [comment]
我到目前为止遇到过一种睡死的情况：睡眠唤醒之后，点击下面的叉再次进入睡眠，然后就睡死了。其余的正常。我暂时也没有解决方案。

**Comment by BrushXue** [comment]
上网研究了一圈，HD530睡死是通病，建议购买独立显卡解决。

**Comment by fishlzhy** [comment]
好的，我会配一块的，感谢您！

Guanyang Xue <notifications@github.com> 于2020年3月6日周五 下午12:39写道：
