### ISSUE TITLE
Audio after sleep issues

### ISSUE THREAD

**Issue by willecko610** [BrushXue/Z170i-Pro-Gaming-Hackintosh#3]
Thanks for your sharing.
很庆幸和你的主板一样，同为华硕z170i-pro-gaming，通过Clover Configurator声卡注入“ID：1”选择reset HDA后声卡驱动了，但音响的3.5mm线并不能接在主板绿色音频插孔，而是得接在黑色插孔选择“线路输出”才有声音。这个倒不算问题，不影响使用。关键是睡眠唤醒后，似乎声卡不工作了，所有与声音有关的程序，比如音乐app，或者在线视频，只要睡眠唤醒点继续播放就会卡住，得强制关闭程序重启后声音才恢复。即使不用板载声卡ALC1150，使用USB外接DAC声卡也同样会出现唤醒无声卡住的问题。请教怎么破？还是我设置有问题，谢谢！

**Comment by BrushXue** [comment]
先试一下BIOS更新到最新？然后BIOS里关于声卡部分有一些参数，我都是默认值。我这边睡眠唤醒的声音到现在还没出过问题。

**Comment by willecko610** [comment]
我bios里关于声卡的设定HD audio controller选 enabled，Front Panel Type选HD Audio，Spdif out type选spdif，depop选Enabled，请教和你的默认设置一样么？

**Comment by willecko610** [comment]
通过把config设置成和你的一样后，完美解决“内置扬声器”和“唤醒无声”问题，灰常感谢！
